# Generated by Django 3.0.3 on 2020-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='mypic', upload_to='uploads/'),
        ),
    ]
