# Generated by Django 3.0.1 on 2020-03-02 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_cart_uid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='uid',
            new_name='sno',
        ),
    ]
