# Generated by Django 3.0.1 on 2020-03-02 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200302_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sno',
        ),
    ]
