# Generated by Django 2.1.7 on 2020-03-02 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cart_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='reporter',
        ),
    ]
