# Generated by Django 2.1.7 on 2020-03-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_cart_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='reporter',
        ),
    ]
