# Generated by Django 3.1 on 2020-08-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20200818_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Account',
            fields=[
                ('Company_Account_id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Account_Name', models.CharField(default='Name', max_length=200)),
                ('Company_Account_Email', models.EmailField(max_length=254)),
                ('Company_Account_Image', models.ImageField(default='mypic', upload_to='CompanyAccount/')),
                ('Company_Account_Desc', models.TextField(default='Desc')),
                ('created_At', models.DateTimeField(auto_now_add=True, null=True)),
                ('Service_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.service_category')),
            ],
        ),
    ]
