# Generated by Django 3.1 on 2020-08-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_company_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_account',
            old_name='Company_Account_Image',
            new_name='Company_Account_logo',
        ),
        migrations.AddField(
            model_name='company_account',
            name='Company_Adress',
            field=models.TextField(default='Adress'),
        ),
    ]
