# Generated by Django 3.1 on 2020-08-19 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Company_Account_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_account'),
        ),
        migrations.AddField(
            model_name='service',
            name='Company_Account_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_account'),
        ),
    ]
