# Generated by Django 3.1 on 2020-08-19 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20200819_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Job_id', models.AutoField(primary_key=True, serialize=False)),
                ('Job_Name', models.CharField(default='Name', max_length=200)),
                ('Job_Description', models.TextField(default='Desc')),
                ('Job_Image', models.ImageField(default='mypic', upload_to='Job/')),
                ('Job_Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Experience_Required', models.CharField(default='0', max_length=120)),
                ('Email', models.EmailField(max_length=254)),
                ('Contact', models.CharField(default='contact', max_length=120)),
                ('category', models.CharField(choices=[('highpaidjobs', 'High Paid Jobs'), ('recentjob', 'Recent job'), ('parttimejob', 'Parttime Job')], default='product', max_length=120)),
                ('Company_Account_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_account')),
            ],
        ),
    ]
