# Generated by Django 3.1 on 2020-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_account',
            name='Contact',
            field=models.CharField(default='contact', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='Contact',
            field=models.CharField(default='contact', max_length=120),
        ),
        migrations.AddField(
            model_name='service',
            name='Email',
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
    ]
