# Generated by Django 3.1 on 2020-08-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20200819_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_account',
            name='Company_Location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AddField(
            model_name='company_account',
            name='Company_Whatsapp_No',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='Location',
            field=models.CharField(default='location', max_length=100),
        ),
        migrations.AddField(
            model_name='user_signup',
            name='Whatsapp_No',
            field=models.IntegerField(default='0'),
        ),
    ]
