# Generated by Django 3.1 on 2020-08-21 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_user_contatact_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_contatact_service',
            old_name='User_Contatact_Service',
            new_name='User_Contatact_Service_id',
        ),
        migrations.CreateModel(
            name='User_Contatact_Job',
            fields=[
                ('User_Contatact_Job_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(default='Name', max_length=255)),
                ('lname', models.CharField(default='Name', max_length=100)),
                ('email', models.EmailField(default='Email', max_length=50)),
                ('password', models.CharField(default='Password', max_length=100)),
                ('address', models.CharField(default='adress', max_length=120)),
                ('city', models.CharField(default='City', max_length=120)),
                ('district', models.CharField(default='District', max_length=120)),
                ('phoneno', models.CharField(default='No', max_length=120)),
                ('Whatsapp_No', models.IntegerField(default='0')),
                ('Location', models.CharField(default='location', max_length=100)),
                ('Desc', models.TextField(default='Desc')),
                ('Comapnay_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_account')),
                ('Job_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.job')),
                ('User_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user_signup')),
            ],
        ),
    ]
