# Generated by Django 3.1 on 2020-08-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20200821_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_account',
            name='Company_Whatsapp_No',
            field=models.CharField(default='0', max_length=120),
        ),
        migrations.AlterField(
            model_name='user_signup',
            name='Whatsapp_No',
            field=models.CharField(default='0', max_length=120),
        ),
    ]
