# Generated by Django 3.1 on 2020-08-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20200821_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_contatact_service',
            name='Whatsapp_No',
            field=models.CharField(default='No', max_length=120),
        ),
    ]
