# Generated by Django 3.1 on 2020-08-22 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20200822_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_contatact_job',
            name='Whatsapp_No',
            field=models.CharField(default='No', max_length=120),
        ),
    ]
