# Generated by Django 3.1 on 2020-08-23 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_order_comapnay_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Company_Account_Id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company_account'),
        ),
    ]
