# Generated by Django 3.1 on 2020-08-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_category_company_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Ordertime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
