# Generated by Django 3.1 on 2020-08-24 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20200824_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Comapnay_Id',
        ),
    ]
