# Generated by Django 3.1 on 2020-08-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20200825_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='products',
        ),
        migrations.DeleteModel(
            name='signup',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
