# Generated by Django 3.1 on 2020-08-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_auto_20200825_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Product_Quantity',
            field=models.FloatField(default=0, max_length=120),
        ),
    ]
