# Generated by Django 3.1 on 2020-08-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_auto_20200825_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_account',
            name='password',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('NotDelivered', 'NotDelivered'), ('reject', 'Reject')], default='Started', max_length=120),
        ),
    ]
