# Generated by Django 3.1 on 2020-08-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_company_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_category',
            name='category',
            field=models.CharField(choices=[('product', 'Products Sale'), ('service', 'Service'), ('jobs', 'Jobs')], default='product', max_length=120),
        ),
    ]
