# Generated by Django 3.1 on 2020-08-28 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20200825_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_account',
            old_name='Service_Category',
            new_name='Service_Category_id',
        ),
    ]
